from MakimaDevil import DEV_USERS, DEVILS, ANGELS, KILLERS, SENSEI, telethn

IMMUNE_USERS = DEVILS + SENSEI + ANGELS + KILLERS + DEV_USERS

IMMUNE_USERS = (
    list(DEVILS) + list(SENSEI) + list(ANGELS) + list(KILLERS) + list(DEV_USERS)
)
