from MakimaDevil import KNIGHTS, DEVILS, ANGELS, KILLERS, SENSEI, telethn

IMMUNE_USERS = DEVILS + SENSEI + ANGELS + KILLERS + KNIGHTS

IMMUNE_USERS = (
    list(DEVILS) + list(SENSEI) + list(ANGELS) + list(KILLERS) + list(KNIGHTS)
)
